title: Hetlevikåsen 51
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/mini-media-player/mini-media-player.js?v=0.8.8
    type: module

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed


# Exclude entities from "Unused entities" view
excluded_entities:
views:
  - title: Hjem
    theme: midnight

    cards:
      - type: glance
        column_width: calc(100% / 4)
        show_state: false
        title: Lys
        entities:
          - entity: light.stue
            tap_action: toggle
          - entity: light.gulvlampe
            tap_action: toggle
          - entity: light.taklys_soverom
            tap_action: toggle
          - entity: light.gang
            tap_action: toggle

      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: input_boolean.light_scene_cold_switch
            tap_action: toggle
          - type: entity-button
            entity: input_boolean.light_scene_everyday_switch
            tap_action: toggle
          - type: entity-button
            entity: input_boolean.light_scene_relaxing_switch
            tap_action: toggle
          - type: entity-button
            entity: input_boolean.good_night_switch
            tap_action: toggle
            
            



      - type: glance
        column_width: calc(100% / 2)
        show_state: false
        entities:
          - binary_sensor.sensor_3  
      #gang
          - binary_sensor.sensor 

      - type: entity-filter
        title: Musikk
        entities:
          - entity: media_player.kitchen
            type: "custom:mini-media-player"
            group: true
          - entity: media_player.living_room
            type: "custom:mini-media-player"
            group: true
          - entity: media_player.bathroom
            type: "custom:mini-media-player"
            group: true
          - entity: media_player.bedroom
            type: "custom:mini-media-player"
            group: true
        state_filter: 
          - "playing"




      - type: picture-entity
        image: /local/images/vacuum.png
        show_state: true
        entity: vacuum.xiaomi_vacuum_cleaner

      - type: history-graph
        entities: 
          - entity: sensor.temperatur__kontor
            name: Kontor
          - entity: sensor.temperatur__soverom
            name: Soverom
          # Hvorfor legges ikke denne inn i grafen med de andre??? 
          #- entity: sensor.fibaro_system_fgsd002_smoke_sensor_temperatur
          #  name: Stue
        hours_to_show: 48
        title: Temperatur 48h
        




   
    

### LIVING ROOM VIEW ###
  - icon: mdi:sofa
    cards:
      - type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - light.stue
          - light.gulvlampe

      - type: custom:mini-media-player
        entity: media_player.living_room
        name: Sonos Playbar
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true

### BEDROOM ROOM VIEW ###
  - icon: mdi:bed-empty
    cards:
      - type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - light.taklys_soverom
          - light.sengelampe_erlend
          - light.sengelampe_stina
          - light.accf2399207e_192168145

      - type: custom:mini-media-player
        entity: media_player.bedroom
        name: Sonos One
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true

### KITCHEN VIEW ###
  - icon: mdi:pot-mix
    cards:
      - type: custom:mini-media-player
        entity: media_player.kitchen
        name: Sonos One
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true


### BATHROOM VIEW ###
  - icon: mdi:shower
    cards:
      - type: custom:mini-media-player
        entity: media_player.bathroom
        name: Sonos One
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true


### AUTOMATIONS VIEW ###
  - icon: mdi:home-automation
    cards:
      - type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - automation.skrur_av_alle_lys_etter_10_minutter
          - automation.nattlys

      - type: entities
        title: Steam
        show_header_toggle: true
        entities:
          - automation.hans_petter_er_online
          - automation.torgrim_er_online
          - automation.tormod_er_online
          - automation.christian_er_online
          - automation.simon_er_online
