title: Hetlevikåsen 51
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/mini-media-player/mini-media-player-bundle.js?v=1.0.3
    type: module
  - url: /local/monster-card/monster-card.js?v=0.2.3
    type: js
  - url: /local/mini-graph-card-bundle.js?v=0.2.1
    type: module


# Exclude entities from "Unused entities" view
excluded_entities:
views:


#############################
#                           #
#                           #
#        DEFAULT VIEW       #
#                           #
#                           #
#############################

  - id: 0  # Automatically created id
    title: Hjem

    cards:
      - id: cf9be913cfa0411884158c526242c893  # Automatically created id
        type: glance
        column_width: calc(100% / 4)
        show_state: false
        title: Lys
        entities:
          - entity: light.stue
            tap_action: #toggle
              action: toggle 
          - entity: light.gulvlampe
            tap_action: 
              action: toggle
          - entity: light.taklys_soverom
            tap_action:
              action: toggle
          - entity: light.gang
            tap_action: 
              action: toggle

      - id: d0e7698b33b3477c8220a225eff0fcbd  # Automatically created id
        type: horizontal-stack
        cards:
          - type: entity-button
            entity: input_boolean.light_scene_everyday_switch
            tap_action: 
              action: toggle
          - type: entity-button
            entity: input_boolean.light_scene_cold_switch
            tap_action: 
              action: toggle
          - type: entity-button
            entity: input_boolean.light_scene_relaxing_switch
            tap_action: 
              action: toggle
          - type: entity-button
            entity: input_boolean.good_night_switch
            tap_action: 
              action: toggle


      - id: f7da027311684c629ac9695a92c2ea41  # Automatically created id
        type: glance
        column_width: calc(100% / 3)
        show_state: false
        entities:
          - entity: binary_sensor.sensor_3
      #gang
          - entity: binary_sensor.sensor
          - entity: binary_sensor.sensor_2

      - type: custom:mini-media-player
        entity: media_player.kitchen
        group: true
        hide:
          power: true
        sonos:
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Stue
            - entity_id: media_player.bathroom
              name: Bad
            - entity_id: media_player.bedroom
              name: Soverom



      - id: e45f693488c04bcf83bbf2f991f41e4b  # Automatically created id
        type: picture-entity
        image: /local/images/vacuum.png
        show_state: true
        entity: vacuum.xiaomi_vacuum_cleaner

#      - type: glance
#        entities:
#          - entity: device_tracker.erlendsiniphone
#           name: Erlend
#            icon: mdi:human-handsup
  
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Forbruk
            entities: !secret tibber_consumption
            line_color: blue
            line_width: 8
            font_size: 75
          - type: custom:mini-graph-card
            name: I dag
            entities: sensor.tibber_accumulated_consumption
            line_color: '#e74c3c'
            line_width: 8
            font_size: 75
            icon: mdi:power-plug
          - type: custom:mini-graph-card
            name: I dag
            entities: sensor.tibber_accumulated_cost
            line_color: var(--accent-color)
            line_width: 8
            font_size: 75
            icon: mdi:currency-usd


#############################
#                           #
#                           #
#     LIVING ROOM VIEW      #
#                           #
#                           #
#############################

  - id: 1  # Automatically created id
    icon: mdi:sofa
    cards:
      - id: c3a1d35bb85143369eedf6df62a0c728  # Automatically created id
        type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - light.stue
          - light.gulvlampe

#      - type: media-control
#        entity: media_player.stua

      - type: custom:mini-media-player
        entity: media_player.living_room
        name: Sonos Playbar
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true



#############################
#                           #
#                           #
#       BED ROOM VIEW       #
#                           #
#                           #
#############################

  - id: 2  # Automatically created id
    icon: mdi:bed-empty
    cards:
      - id: 20207687509240e18d0ec014e45e1728  # Automatically created id
        type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - light.taklys_soverom
          - light.tradfri_bulb_2_2
          - light.sengelampe_stina
          - light.accf2399207e_192_168_1_45
          
      - type: entities
        title: Vekkerklokke
        show_header_toggle: false
        entities:
          - automation.hverdagsalarm_06_30
          - input_boolean.alarm_clock_status
          - sensor.alarm_clock_time
          - input_number.alarm_clock_hour
          - input_number.alarm_clock_minute
          - input_number.alarm_clock_fade_in_minutes 

      - id: 3d8c55941e6742a6b2937433ab60d34d  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.bedroom
        name: Sonos One
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true
        

                

#############################
#                           #
#                           #
#        KITCHEN VIEW       #
#                           #
#                           #
#############################

  - id: 3  # Automatically created id
    icon: mdi:pot-mix
    cards:
      - id: 4cd5552ea1de4cfd922b724d064a7f02  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.kitchen
        name: Sonos One
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true

      - id: b8d87e646ebd49a38817acd09ec3e844  # Automatically created id
        type: glance
        show_state: false
        entities:
          - entity: script.vacuum_kitchen
            tap_action: toggle
          - entity: script.vacuum_empty
            tap_action: toggle


#############################
#                           #
#                           #
#      BATHROOM VIEW        #
#                           #
#                           #
#############################

  - id: 4  # Automatically created id
    icon: mdi:shower
    cards:
      - id: d5696cd94c0848c08dc906756128707b  # Automatically created id
        type: custom:mini-media-player
        entity: media_player.bathroom
        name: Sonos One
        artwork: cover
        power_color: true
        hide_volume: false
        show_progress: true



#############################
#                           #
#                           #
#     AUTOMATIONS VIEW      #
#                           #
#                           #
#############################

  - id: 5  # Automatically created id
    icon: mdi:home-automation
    cards:
      - id: 636df89c227a41d2a0596a0263bfbe91  # Automatically created id
        type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - automation.skrur_av_alle_lys_etter_10_minutter
          - automation.nattlys
          - automation.lys_i_gangen
          - automation.dor_er_aapen
          - automation.bevegelse_detektert_i_gangen
          #- automation.skru_av_lys_i_gangen

      - type: entities
        title: Diverse
        show_header_toggle: false
        entities:
          - input_boolean.vacuum_every_weekday
          - input_boolean.sonos_join_speakers




# Funker ikke, får opp feilmelding. Er komponentene installert korrekt?
#      - id: a44697bc92b24ee89e601ef6d157020c  # Automatically created id
#        type: custom:monster-card
#        title: Ødelagt?
#        filter:
#          exclude:
#            - {domain: group}
#          include:
#            - {state: unknown}
#            - {state: unavailable}
#        show_empty: false
