title: Hetlevikåsen 51
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed


# Exclude entities from "Unused entities" view
excluded_entities:
views:
  - title: Hjem
    # Optional unique id for direct access /lovelace/${id}
    id: example
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode

    cards:
      - type: glance
        column_width: calc(100% / 4)
        show_state: false
        title: Lys
        entities:
          - entity: light.stue
            tap_action: toggle
          - entity: light.gulvlampe
            tap_action: toggle
          - entity: light.taklys_soverom
            tap_action: toggle
          - entity: light.gang
            tap_action: toggle

      - type: glance
       # column_width: calc()
        show_state: false
        #title: Bevegelse
        entities:
          - binary_sensor.sensor_3  
      #gang
          - binary_sensor.sensor 

      - type: glance
        column_width: calc(100% / 4)
        show_state: true
        title: Støvsuger
        entities:
          - vacuum.xiaomi_vacuum_cleaner
          - script.vacuum_kitchen
          - script.vacuum_empty
          - entity: input_boolean.vacuum_every_weekday
            tap_action: toggle
   
    

### SECOND VIEW ###
  - icon: mdi:sofa
    cards:
      - type: entities
        title: Lys
        show_header_toggle: false
        entities:
          - light.stue
          - light.gulvlampe



#
