
auto_motion_group:
  name: Bevegelsessensor
  entities:
    - automation.bevegelse_detektert_i_gangen
    - automation.bevegelse_detektert_i_stuen

auto_light_group:
  name: Lys
  entities:
    - automation.skrur_av_alle_lys_etter_10_minutter
    - automation.nattlys